/**
 * Darshan Experience Engine — the Gita Quote Reflection source.
 *
 * `data/quotes.json` is the seed for the `gita_quotes` CMS table. It is
 * generated by `scripts/gen_quotes.js`, which copies Sanskrit, transliteration
 * and Hindi verbatim out of `data/verses.json` (the app's own corpus) and pairs
 * them with a curated plain-language English meaning plus theme/mood metadata.
 * Nothing here is fetched from the web at runtime, so the hero's first paint
 * costs no network round-trip.
 *
 * TODO(cms): when `gita_quotes` is live, replace `loadQuotes()` with a cached
 * server fetch and keep this JSON as the offline fallback — same fail-open
 * contract as everything else in the app.
 */
import raw from '@/data/quotes.json'
import { ALL_QUOTE_THEMES, moodForTheme, moodOf } from './registry'
import type { GitaQuote, QuoteTheme, VisualMood } from './types'

const ALL: GitaQuote[] = ((raw as { quotes: GitaQuote[] }).quotes || [])
  .filter((q) => q.active_status)
  .sort((a, b) => b.display_priority - a.display_priority)

export function loadQuotes(themes: QuoteTheme[] = []): GitaQuote[] {
  if (!themes.length) return ALL
  const wanted = new Set(themes)
  const filtered = ALL.filter((q) => wanted.has(q.theme))
  // Never hand back an empty list — a mis-set theme filter must not blank the hero.
  return filtered.length ? filtered : ALL
}

export function quoteByReference(reference: string): GitaQuote | undefined {
  return ALL.find((q) => q.reference === reference)
}

export function quotesForTheme(theme: QuoteTheme): GitaQuote[] {
  return ALL.filter((q) => q.theme === theme)
}

/**
 * A stable quote-of-the-day: the same seeker sees the same shloka all day, and
 * it changes at midnight. Deterministic (no randomness) so server and client
 * agree — important, because a mismatch would hydrate-error the hero.
 */
export function dailyQuote(quotes: GitaQuote[] = ALL, date = new Date()): GitaQuote {
  if (!quotes.length) return ALL[0]
  const start = Date.UTC(date.getUTCFullYear(), 0, 0)
  const dayOfYear = Math.floor((Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate()) - start) / 86_400_000)
  return quotes[dayOfYear % quotes.length]
}

/** The visual mood a quote should paint the scene with. */
export function moodForQuote(quote: GitaQuote | undefined): VisualMood {
  if (!quote) return moodOf(undefined)
  return quote.mood ? moodOf(quote.mood) : moodForTheme(quote.theme)
}

export { ALL_QUOTE_THEMES }
export type { GitaQuote, QuoteTheme }
